### ISSUE TITLE
Overall Goal

### ISSUE THREAD

**Issue by rhinostudios** [pixelpicosean/lesser-panda#28]
So with this Lesser Panda 
What is the goal to become a modern replacement for Flash. 
Flash work on PC
Lesser panda work on PC, xbox, Android. Ios

**Comment by pixelpicosean** [comment]
Nope, it's just another framework for game development. My goal is to build a powerful engine with tons of features, so you can get start in no time.

From v1.x I start to align the API design to [impact.js](http://impactjs.com/) which is my favorite engine so far. It is simple, clear and flexible. But it is not open sourced, and not fast enough in some cases.

And I also want to port it to C++ so we get a native engine with almost same API. The main reason I decided to create my own instead of using (say Oxygine, Cocos2D-x...) is that their design is old fashion and focus too much on **object oriented**.

As an HTML5 game framework, LesserPanda something equivalents Flixel/Flashpunk instead of Flash.

**Comment by rhinostudios** [comment]
Good i too dont like having to write and rewrite code to make object oriented. Functional i prefer. Im in Tunis this week on Holiday.
Hope to get more done when im back ;)

For good C++ Website check 
Grrlib.santo.fr
